version: '3.8'

services:
  app:
    image: nicollaspierre/goodvideo-autenticacao:latest
    hostname: goodvideo-auth
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://goodvideo-usuario-rds.czn98nozvza3.us-east-1.rds.amazonaws.com:5432/usuario
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres