spring:
  application:
    name: GoodVideo-Autenticacao
  datasource:
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driverClassName: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://goodvideo-usuario-rds.czn98nozvza3.us-east-1.rds.amazonaws.com:5432/usuario}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  packagesToScan: com.good.video
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

api:
  security:
    token:
      secret: ${JWT_SECRET:secret}