apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DATABASE_USER: cG9zdGdyZXM=
  DATABASE_PASSWORD: cG9zdGdyZXM=
  DATABASE_URL: amRiYzpwb3N0Z3Jlc3FsOi8vZ29vZHZpZGVvLXVzdWFyaW8tcmRzLmN6bjk4bm96dnphMy51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jb206NTQzMi91c3Vhcmlv