apiVersion: v1
kind: Service
metadata:
  name: goodvideo-auth-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: goodvideo-auth
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080